#!/usr/bin/env bash

# This bash script deploys the  application.

# We want this entire script to exit if any single line fails.
# So we set the `-e` flag.
set -e

# If our deploy fails partway through we want to clean up after ourselves.
# This next block is like a try/catch for our entire script.

# We trap any program EXIT and run this function.
# Whether the deploy succeeds or fails, we'll clean up the deploy branch.

function cleanup_at_exit {
  # return to your master branch
  git checkout master

  # remove the deploy branch
  git branch -D deploy
}
trap cleanup_at_exit EXIT

# checks out a new branch called "deploy". The name "deploy" needs to match
# the name of the branch we specify when we push to our heroku remote.
git checkout -b deploy

# create a commit, even if nothing changed
git commit --allow-empty -m 'Deploying'

# push local "deploy" branch to the "master" branch on heroku
git push --force heroku deploy:master
